[package]
name = "bevy_xpbd_3d_extras"
authors = ["PixelDots"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_xpbd_3d = "0.4"

[profile.dev]
opt-level = 1
